export default [
  {
    'id': 1,
    'date': '07/04/2019',
    'class': 'Falcon 59',
    'helmHours': 2,
    'crewHours': 0,
    'windSpeed': 6,
    'type': 'Race: FF',
  },
  {
    'id': 2,
    'date': '05/05/2019',
    'class': 'Falcon 59',
    'helmHours': 1,
    'crewHours': 2,
    'windSpeed': 4,
    'type': 'Race: FF',
  },
  {
    'id': 3,
    'date': '19/05/2019',
    'class': 'Laser 2000',
    'helmHours': 3,
    'crewHours': 1,
    'windSpeed': 5,
    'type': 'Race: FF',
  },
  {
    'id': 4,
    'date': '01/06/2019',
    'class': 'Falcon 59',
    'helmHours': 2,
    'crewHours': 1,
    'windSpeed': 4,
    'type': 'Race: Windermere',
  },
  {
    'id': 5,
    'date': '02/06/2019',
    'class': 'Feva RS',
    'helmHours': 2,
    'crewHours': 1,
    'windSpeed': 4,
    'type': 'Race: Windermere',
  },
  {
    'id': 6,
    'date': '30/06/2019',
    'class': 'Feva RS',
    'helmHours': 2,
    'crewHours': 0,
    'windSpeed': 6,
    'type': 'Race: Wallasey',
  },
  {
    'id': 7,
    'date': '07/07/2019',
    'class': 'Falcon 59',
    'helmHours': 1,
    'crewHours': 2,
    'windSpeed': 5,
    'type': 'Race: WK',
  },
  {
    'id': 8,
    'date': '05/09/2019',
    'class': 'Falcon 59',
    'helmHours': 3,
    'crewHours': 1,
    'windSpeed': 3,
    'type': 'Race: FF',
  },
  {
    'id': 9,
    'date': '15/09/2019',
    'class': 'Laser Pico',
    'helmHours': 2,
    'crewHours': 1,
    'windSpeed': 4,
    'type': 'Race: FF',
  },
]
